Make the url generator available on the events
prestaconcept/PrestaSitemapBundle pull request #287
Opened 2021-10-22 19:02 UTC by kbond

Fixes #286. Tests pass still so hopefully that means this is BC. Before I finalize, I'd like to ensure this direction is acceptable.

TODO:
- [x] Add tests
- [x] Trigger deprecation warnings
- [x] Document

2021-10-22 19:03 UTC, kbond commented on src/Event/SitemapPopulateEvent.php
> +    public function __construct(UrlContainerInterface $urlContainer, string $section = null, UrlGeneratorInterface $urlGenerator = null)
Thinking we could trigger a deprecation warning if `$urlGenerator` is null - WDYT?

2021-10-22 19:04 UTC, kbond commented on src/Event/SitemapAddUrlEvent.php
> +    public function __construct(string $route, array $options, UrlGeneratorInterface $urlGenerator = null)
I assumed you would want this even to include the `$urlGenerator` as well. If so, we should trigger a deprecation warning here when it is null.

2021-10-22 19:04 UTC, kbond commented on src/Service/AbstractGenerator.php
> +    public function __construct(EventDispatcherInterface $dispatcher, int $itemsBySet = null, UrlGeneratorInterface $urlGenerator = null)
Trigger deprecation when `null` here?

2021-10-27 18:46 UTC, yann-eugone requested changes
Sorry I'm late (long weekend :))

I think this is a very good start, thank you.

Do you planned to update/add tests in the same PR ?

2021-10-27 18:46 UTC, yann-eugone commented on src/Event/SitemapAddUrlEvent.php
> +    public function __construct(string $route, array $options, UrlGeneratorInterface $urlGenerator = null)
Not sure what would be the use case here, but why not.

But yes I think a deprecation should be triggered here if `$urlGenerator` is null.

2021-10-27 18:46 UTC, yann-eugone commented on src/Event/SitemapAddUrlEvent.php
> +    public function getUrlGenerator(): ?UrlGeneratorInterface
IMO we should have a strict return type, and throw an exception if property is null.

Something that tell the developer what he did wrong.

2021-10-27 18:46 UTC, yann-eugone commented on src/Event/SitemapPopulateEvent.php
> +    public function __construct(UrlContainerInterface $urlContainer, string $section = null, UrlGeneratorInterface $urlGenerator = null)
Yes, 100% agreed

2021-10-27 18:46 UTC, yann-eugone commented on src/Event/SitemapPopulateEvent.php
> +    public function getUrlGenerator(): ?UrlGeneratorInterface
Same has above: strict return type, and throw an exception if property is null.

2021-10-27 18:46 UTC, yann-eugone commented on src/Service/AbstractGenerator.php
> +    public function __construct(EventDispatcherInterface $dispatcher, int $itemsBySet = null, UrlGeneratorInterface $urlGenerator = null)
Yes, here too

2021-10-27 18:50 UTC, kbond commented on src/Event/SitemapAddUrlEvent.php
> +    public function getUrlGenerator(): ?UrlGeneratorInterface
Perfect, I thought the same thing.

2021-10-27 18:50 UTC, kbond commented
> Do you planned to update/add tests in the same PR ?

Yes, that was my plan.

2021-10-27 20:01 UTC, kbond commented
Ok, addressed the comments. Let me know if you'd like me to change the deprecation/exception messages.

For the tests, I was thinking the following:
1. Mock/inject the `UrlGeneratorInterface` in the unit tests to remove the self-deprecations
2. Adjust the integration test's `SitemapListener` to use the url generator from the event (instead of injecting)

Let me know if you'd like anything else.

2021-10-28 07:22 UTC, yann-eugone commented
>     1. Mock/inject the `UrlGeneratorInterface` in the unit tests to remove the self-deprecations

I know that this bundle has some bad practices in tests, but I'm trying to fix this.
I'm trying to apply the "don't mock what you don't own" approach.
I suggest you inject an implementation of the UrlGeneratorInterface, some actual object from symfony ecosystem, or a test dummy you will create.

>     2. Adjust the integration test's `SitemapListener` to use the url generator from the event (instead of injecting)

:+1:, 100% agree with this

2021-10-28 07:22 UTC, yann-eugone requested changes

2021-10-28 07:22 UTC, yann-eugone commented on src/Event/SitemapAddUrlEvent.php
> +    public function __construct(string $route, array $options, UrlGeneratorInterface $urlGenerator = null)
Night passed, I'm wondering whether these deprecations at the event level are making sense.

We agree that this is a DX thing ?
A developer that rely on an event the bundle produces will be able to use this feature.
But if he do not want to use this feature and produces is own event, we don't care, do we ?

2021-10-28 07:22 UTC, yann-eugone commented on composer.json
> +        "symfony/deprecation-contracts": "^2.4"
I'm not a big fan of adding a dependency in a minor version.
We usually have issues with dependencies version compatibility : X requires Y 1.x, but Z requires Y 2.x

So far we did not used this library, we were triggering deprecations manually.
Do you think you can go back to that strategy ?

2021-10-28 12:24 UTC, kbond commented on src/Event/SitemapAddUrlEvent.php
> +    public function __construct(string $route, array $options, UrlGeneratorInterface $urlGenerator = null)
Sure, that's fair. I'll remove.

2021-10-28 12:26 UTC, kbond commented on composer.json
> +        "symfony/deprecation-contracts": "^2.4"
Sure, I can do this.

2021-10-28 13:00 UTC, kbond commented
Ok, I believe this is ready for a final review. I believe the phpstan errors are unrelated.

2021-10-29 06:15 UTC, yann-eugone approved these changes
Thank you for this work !

2021-10-29 06:15 UTC, merged